8 task
helmy-er/itechart-rails-course pull request #5
Opened 2021-12-25 11:59 UTC by helmy-er

to check

2021-12-27 12:35 UTC, e-popolamov requested changes
please fix all places where i leave comment and check other places for identical problems

2021-12-27 12:35 UTC, e-popolamov commented on app/controllers/buffers_controller.rb
> +    @buffer = Buffer.find(params[:id])
if i pass wrong id - this place raise error
fix and add spec

2021-12-27 12:35 UTC, e-popolamov commented on app/controllers/categories_controller.rb
> +      Buffer.create(category_id: 1, person_id: params.require(:people_id)).save(validate: false)
why u use `id:1`? this is very bad style
also why everywhere `validation: false`

2021-12-27 12:35 UTC, e-popolamov commented on app/controllers/categories_controller.rb
> +    @person_id = Buffer.find_by(category_id: params.require(:format)).person_id
what if `.find_by` return nil?

2021-12-27 12:35 UTC, e-popolamov commented on app/controllers/categories_controller.rb
> +    name = params[:category].permit(:name)[:name]
wrong using strong params

2021-12-27 12:35 UTC, e-popolamov commented on app/controllers/categories_controller.rb
> +    if name != ''
`if name.present?`

2021-12-27 12:35 UTC, e-popolamov commented on app/controllers/categories_controller.rb
> +        all_people.each { |a| Buffer.create(category_id: Category.last.id + 1, person_id: a.id).save(validate: false) }
bad case when you increment id

2021-12-27 12:35 UTC, e-popolamov commented on app/controllers/categories_controller.rb
> +    category_id.each do |i|
please use meaning names

2021-12-27 12:35 UTC, e-popolamov commented on app/controllers/categories_controller.rb
> +    category_id = params[:category].require(:category_id).drop(1)
i think u can refactor this method

2022-01-04 08:13 UTC, helmy-er commented on app/controllers/buffers_controller.rb
> +    @buffer = Buffer.find(params[:id])
completed

2022-01-04 08:13 UTC, helmy-er commented on app/controllers/categories_controller.rb
> +      Buffer.create(category_id: 1, person_id: params.require(:people_id)).save(validate: false)
completed

2022-01-04 08:13 UTC, helmy-er commented on app/controllers/categories_controller.rb
> +    @person_id = Buffer.find_by(category_id: params.require(:format)).person_id
completed

2022-01-04 08:13 UTC, helmy-er commented on app/controllers/categories_controller.rb
> +    name = params[:category].permit(:name)[:name]
completed

2022-01-04 08:13 UTC, helmy-er commented on app/controllers/categories_controller.rb
> +    if name != ''
completed

2022-01-04 08:13 UTC, helmy-er commented on app/controllers/categories_controller.rb
> +        all_people.each { |a| Buffer.create(category_id: Category.last.id + 1, person_id: a.id).save(validate: false) }
completed

2022-01-04 08:13 UTC, helmy-er commented on app/controllers/categories_controller.rb
> +    category_id.each do |i|
completed

2022-01-04 08:13 UTC, helmy-er commented on app/controllers/categories_controller.rb
> +    category_id = params[:category].require(:category_id).drop(1)
completed

2022-01-06 12:13 UTC, e-popolamov commented on app/controllers/categories_controller.rb
> +        names_of_income.append(Category.find(i).name) unless Category.find(i).status
`unless Category.find(i).status` always is false. this validation needed?

2022-01-06 12:13 UTC, e-popolamov commented on app/controllers/categories_controller.rb
> +    category_id.each do |i|
please use meaningful name. instead of `i` use `id` for example

2022-01-06 12:13 UTC, e-popolamov commented on app/controllers/expenses_controller.rb
> +      @note_expenses.append(a) unless a.text.delete(' ').empty?
instead of `.delete(' ')` use https://apidock.com/ruby/String/strip

2022-01-06 12:13 UTC, e-popolamov commented on app/controllers/expenses_controller.rb
> +    notes.each do |a|
use `note` instead of `a`

2022-01-06 12:13 UTC, e-popolamov commented on app/controllers/expenses_controller.rb
> +    status = params[:expense].require(:status)
but don't forget about status var. u can modify them in method

2022-01-06 12:14 UTC, e-popolamov commented
after u change rubocop.yml please fix new issues

2022-01-06 16:48 UTC, helmy-er commented on .rubocop.yml
> +    - 'app/controllers/categories_controller.rb'
because rubocop doesn't understand where i use some factories and it create offenses

2022-01-06 16:49 UTC, helmy-er commented on .rubocop.yml
> +  Exclude:
fixed

2022-01-06 16:50 UTC, helmy-er commented on .rubocop.yml
> +    - 'app/controllers/expenses_controller.rb'
fixed

2022-01-06 16:51 UTC, helmy-er commented on app/controllers/categories_controller.rb
> +        names_of_income.append(Category.find(i).name) unless Category.find(i).status
fixed

2022-01-06 16:51 UTC, helmy-er commented on app/controllers/categories_controller.rb
> +    category_id.each do |i|
fixed

2022-01-06 16:51 UTC, helmy-er commented on app/controllers/expenses_controller.rb
> +      @note_expenses.append(a) unless a.text.delete(' ').empty?
fixed

2022-01-06 16:51 UTC, helmy-er commented on app/controllers/expenses_controller.rb
> +    notes.each do |a|
fixed

2022-01-06 16:52 UTC, helmy-er commented on app/controllers/expenses_controller.rb
> +    redirect_to expenses_path(params.require(:format)) if @expense.save
fixed

2022-01-06 16:52 UTC, helmy-er commented on app/controllers/expenses_controller.rb
> +    status = params[:expense].require(:status)
fixed

2022-01-06 16:52 UTC, helmy-er commented on app/controllers/expenses_controller.rb
> +    id = params.require(:format)
fixed

2022-01-06 16:52 UTC, helmy-er commented on app/controllers/expenses_controller.rb
> +    @expense.update_attribute('text', atributes[1])
fixed

2022-01-06 16:52 UTC, helmy-er commented on app/helpers/application_helper.rb
> +# frozen_string_literal: true
fixed

2022-01-10 12:37 UTC, e-popolamov requested changes

2022-01-10 12:37 UTC, e-popolamov commented on app/controllers/categories_controller.rb
> +      Buffer.create(category_id: Category.last, person_id: params.require(:people_id)).save
use `.last` it is not a good idea. cuz if u will be have many users `.last` can return not a correct Category. 
add variable for new category and use it for create Buffer.

2022-01-10 12:37 UTC, e-popolamov commented on app/controllers/categories_controller.rb
> +  rescue ActiveRecord::RecordNotFound
this is good decision. but u every time need to add rescue in methods. Better if u will be use `rescue_from` in ApplicationController. 
example: https://gist.github.com/bf4/4381029
Also remind that stack of all `rescue_from` starts from end.

2022-01-10 12:37 UTC, e-popolamov commented on app/controllers/categories_controller.rb
> +    status = params[:category].require(:status) == '1'
usually for params.permit create private method
your will be looks like 
```
def category_params
    params.require(:category).permit('list of params')
end
```
and use this method instead of every time make `require`.
for ex `category_params[:status]`

2022-01-10 12:37 UTC, e-popolamov commented on app/controllers/categories_controller.rb
> +    # hash with income
no needed comment every line. u should leave comment only for hard to understanding places.

2022-01-10 12:37 UTC, e-popolamov commented on app/controllers/categories_controller.rb
> +          unless Category.find(id).status
this unless needed? 
in if branch u already check for `Category.find(id).status`
this validation useless

2022-01-10 12:37 UTC, e-popolamov commented on app/controllers/categories_controller.rb
> +        if Category.find(id).status
your branches for `if` identical 
one difference only in name of variable. maybe better refactor this?

2022-01-10 12:37 UTC, e-popolamov commented on app/controllers/categories_controller.rb
> +    Buffer.all.where(category_id: target_category_id).each(&:delete)
`.all` needed?

2022-01-10 12:37 UTC, e-popolamov commented on app/controllers/categories_controller.rb
> +      if Category.find(id).status
again identical branches. it can be simplified

2022-01-10 12:37 UTC, e-popolamov commented on app/controllers/expenses_controller.rb
> +    notes = target.expenses.all
`target.expenses.all.each { |note| @note_expenses.append(note) unless note.text.blank? } `

2022-01-10 12:37 UTC, e-popolamov commented on app/controllers/expenses_controller.rb
> +    data = params[:expense].require(%i[name summa date])
again about params

2022-01-10 12:37 UTC, e-popolamov commented on app/controllers/expenses_controller.rb
> +    @expense = Expense.new(name: data[0], text:  text,
2 spaces instead of 1

2022-01-11 22:45 UTC, e-popolamov reviewed
It is not so major changes. Please fix this and re-request. 
I think u in right way to finish this tasks

2022-01-11 22:45 UTC, e-popolamov commented on app/controllers/categories_controller.rb
> +    rescue_from ActiveRecord::RecordNotFound, NoMethodError, with: :render_not_found
All your rescue from validate same type of errors. Maybe better move this to ApplicationController level?

2022-01-11 22:45 UTC, e-popolamov commented on app/controllers/expenses_controller.rb
> +    target = Category.find(params.require(:people_id))
if you move ActiveRecord::RecordNotFound rescue to AppController level you can no worry about places like this. Cuz if u pass invalid id to here - method `.find` raise error.

2022-01-11 22:45 UTC, e-popolamov commented on app/controllers/expenses_controller.rb
> +    if @expense.save
`redirect_to @expense.save ? expenses_path(id) : new_expense_path(id)`
looks better

2022-01-11 22:45 UTC, e-popolamov commented on app/controllers/expenses_controller.rb
> +    rescue_from ActiveRecord::RecordNotFound, NoMethodError, with: :render_not_found
same as other

2022-01-11 22:45 UTC, e-popolamov commented on app/controllers/categories_controller.rb
> +  def days_in_month(month, year = Time.now.year)
move this method to private

2022-01-12 12:59 UTC, e-popolamov reviewed
Please add spec for 
people_controller.rb#index
app/controllers/expenses_controller.rb#notes
app/controllers/categories_controller.rb#index
app/controllers/categories_controller.rb#new
app/controllers/categories_controller.rb#edit

2022-01-12 12:59 UTC, e-popolamov commented on app/views/categories/grafik.html.erb
> +<script>
bad style add js code to .erb. better if u move this to another file and include it

2022-01-12 13:00 UTC, e-popolamov commented
Also in ui i can create user with long-long name. I think need add validation for this

2022-01-12 13:01 UTC, e-popolamov commented
If you open category for edit - name is empty. i think problem in route.

2022-01-12 13:03 UTC, e-popolamov commented
Also same problem in a editing expense page

2022-01-12 13:05 UTC, e-popolamov commented
Good idea to add ability to set date for transactions. But u can set date in future. I think it is wrong behavior.

2022-01-12 13:06 UTC, e-popolamov commented
Good work with charts!

2022-01-13 09:57 UTC, e-popolamov approved these changes
It was a hard way, but u pass! Congratulations!
You finished all 8 tasks in time! GJ!

2022-01-13 09:57 UTC, merged